# Practica 04: Análisis de Datos Exploratorio con Python y Jupiter Notebook
**Programa de Estudios:** Ingeniería en Desarrollo y Gestión de Software \
**Asignatura:** Extracción de Conocimiento en Base de Datos \
**Docente:** M.T.I. Marco A. Ramírez Hernández \
**Periodo:** Mayo - Agosto 2026

## Unidad 2: Preparación de los Datos

**Nombre del Estudiante:** Jesús Domínguez Ramírez \
**Matricula:** 230028 \
**Grado y Grupo:** 9°A IDGS
***

El estudiante practicará como realizar un análisis exploratorio de datos, utilizando el lenguaje de programación de Python, y librerías comúnes para la
carga, manipulación, análisis y visualización previa de un conjunto de datos (Dataset), para esta práctica se utilizarán las librerías de:
- Pandas
- Numpy
- Seaborn
- OS
- Matplotlib

1. Importar las librerías necesarias para realizar el EDA

Comenzamos por importar la librería que nos permitirá manipular los datos del dataset extraidos de una fuente de datos (datasource)

In [3]:
import pandas as pd

2. Creamos un DataFrame, leyendo el archivo delimitado por comas (.CSV)

In [64]:
pokemons = pd.read_csv('./Pokemon.csv')

3. Imprimimos el resultado de lectura

Este comando imprime en una tabla las columnas y las filas del dataframe, siempre de manera estándar nos mostrará los primeros 5 y los últimos 5 registro del Dataframe

In [65]:
pokemons

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
800,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
801,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
802,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
803,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
804,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

4. Obtener una muestra aleatoria de registros del dataframe usando elmétodo **.sample**

Como parámetro de entrada podemos definir un entero que determina el tamaño de la muestra

In [13]:
pokemons.sample(7) ## Obtiene una  muestra de 7 pokemones aleatoria

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
187,173,Cleffa,Fairy,NaN,218,50,25,28,45,55,15,2,False
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
665,604,Eelektross,Electric,NaN,515,85,115,80,105,80,50,5,False
386,354,Banette,Ghost,NaN,455,64,115,65,83,63,65,3,False
596,536,Palpitoad,Water,Ground,384,75,65,55,65,55,69,5,False
470,423,Gastrodon,Water,Ground,475,111,83,68,92,82,39,4,False
42,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False

**Ejercicio 1:** Obtén una muestra de 50

```pokemons_50 = pokemons.sample(50)```

5. Obtener una muestra de rangos definidos usando **.iloc**

In [21]:
pokemons_100_to_200 = pokemons.iloc[100:200]
pokemons_100_to_200

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
100,93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False
101,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
103,95,Onix,Rock,Ground,385,35,45,160,30,45,70,1,False
104,96,Drowzee,Psychic,NaN,328,60,48,45,43,90,42,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,181,Ampharos,Electric,NaN,510,90,75,85,115,90,55,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
197,182,Bellossom,Grass,NaN,490,75,80,95,90,100,50,2,False
198,183,Marill,Water,Fairy,250,70,20,50,20,50,40,2,False
199,184,Azumarill,Water,Fairy,420,100,50,80,60,80,50,2,False

6. Como saber las columnas o atributos que tiene el Dataframe

In [25]:
pokemons.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

<table>
    <thead>
        <tr>
            <th>Campo</th>
            <th>Descripcion</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <strong>#</strong>:
            </td>
            <td>
                El ID o número de identificación del Pokemon.
            </td>
        </tr>
        <tr>
            <td>
                <strong>Name</strong>:
            </td>
            <td>
                El nombre del Pokémon.
            </td>
        </tr>
        <tr>
            <td>
                <strong>Type 1<strong>:
            </td>
            <td>
                Se refiere a las propiedades elementales (tipos) asociadas tanto al Pokémon como a sus movimientos.
            </td>
        </tr>
        <tr>
            <td>
                <strong>Type 2</strong>:
            </td>
            <td>
                Los Pokémon pueden tener hasta dos tipos (Pokémon de tipo Dual); los movimientos solo pueden tener uno.
            </td>
        </tr>
        <tr>
            <td>
                <strong>Total</strong>: 
            </td>
            <td>
                Representa la suma de todos los stats, lo que te da una idea de qué tan "pesado" o fuerte es el Pokémon
            </td>
        </tr>
        <tr>
        <td>
                <strong>HP</strong>:
            </td>
            <td> (Puntos de Salud) Es qué tanto aguante tiene un Pokémon antes de que lo dejen fuera de combate (se desmaye)
        </tr>
        <tr>
        <td>
                <strong>Attack</strong>:
            </td>
            <td> La fuerza de los ataques físicos del Pokemon
        </tr>
        <tr>
        <td>
                <strong>Defense</strong>:
            </td>
            <td> Qué tanto aguanta el pPokémon contra los ataques físicos del rival
        </tr>
        <tr>
        <td>
                <strong>Sp. Atk</strong>:
            </td>
            <td> Ataque Especial; el poder de los movimientos especiales del Pokémon
        </tr>
        <tr>
            <td>
                <strong>Sp.Def</strong>:
            </td>
            <td>
                Defense Especial; Qué tan resistente es el Pokémon ante los ataques especiales
            </td>
        </tr>
        <tr>
            <td>
                <strong>Speed</strong>:
            </td>
            <td>
                Velocidad; el Pokémon que tenga más velocidad es el que ataca primero
            </td>
        </tr>
        <tr>
        **Generation**: Se refiere a la generación de la serie de juegos a la que pertenece
        </tr>
        <tr>
            <td>
                <strong>Legendary</strong>: 
            </td>
            <td>
                Indica si el Pokémon es Legendario o no (son bichos muy raros y poderosos). Es un valor booleano (sí/no)
            </td>
        </tr>
    </tbody>
</table>

7. Explorar la composición y ausencia de datos (METADATA) con **.info**

La libreria de pandas, incluye un método que nos permite evaluyar el tipo de dato y su composición y ausencia.

In [27]:
pokemons.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

8. Limpieza de Datos.

Dependiendo del objeto del análisis algunas columnas o registro no serán necesarias en nuestro Dataframe, en este caso omitiremos los datos vacios, por los que eliminaremos la columna 'Type 2', y renombraremos la columna 'Type 1' por 'Type'.

In [68]:
del pokemons['Type 2']
pokemons.rename(columns={'Type 1':'Type'}, inplace= True)

In [29]:
pokemons

,#,Name,Type,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,600,80,110,120,130,90,70,6,True

**Ejercicio 02:** Consulta la Metadata de la actualización y compara los cambios con la anterior.

¿Qué cambios ves? Redacta tu respuesta

In [38]:
pokemons.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type        800 non-null    object
 3   Total       800 non-null    int64
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(2)
memory usage: 69.7+ KB

**Cambios**: Cambia el número de columnas del Dataframe. Esto se puede corroborar viendo el contador de la primera columna; el último numero es 11, cuando antes era 12. Igual la columna 'Type' es un renombre de la anterior llamada 'Type 1'. La columna 'Type 2' desaparecio.

9. Visualización de los primeros datos usando el método **.head**.

In [35]:
pokemons.head()

,#,Name,Type,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,309,39,52,43,60,50,65,1,False

**Ejercicio 03**: Muestra los últimos 10 registros del Dataframe

In [41]:
pokemons.tail(10)

,#,Name,Type,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
790,714,Noibat,Flying,245,40,30,35,45,40,55,6,False
791,715,Noivern,Flying,535,85,70,80,97,80,123,6,False
792,716,Xerneas,Fairy,680,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,680,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,600,80,110,120,130,90,70,6,True

10. Estadística básica del Dataframe

Pandas permite emitir un reporte de estadística básica (medidas de tendencia) sobre datos cuantitativos usando el comando **.describe**.

In [71]:
pokemons.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,805.000000,805.000000,805.000000,805.000000,805.000000,805.000000,805.000000,805.000000,805.000000
mean,361.686957,434.592547,69.300621,78.802484,73.750311,72.765217,71.840994,68.132919,3.315528
std,208.184079,119.844107,25.478243,32.471756,31.119670,32.679558,27.763922,29.028781,1.659383
min,1.000000,180.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.000000
25%,183.000000,330.000000,50.000000,55.000000,50.000000,50.000000,50.000000,45.000000,2.000000
50%,362.000000,450.000000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.000000
75%,538.000000,515.000000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.000000
max,721.000000,780.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.000000

11. Calcular el total de datos no duplicados (únicos)

Usaremos **.len()** como función para calcular la longitud del dataframe y **.unique()** para excluir los duplicados.

***NOTA:*** No considerar ID como un atributo de llave primaria, sino el total de columnas como un solo elemento u objeto.

Obteniendo los valores unicos por columna en este caso en la columna "Name"

In [74]:
len(pokemons.Name.unique())

800

Obteniendo el total de objetos (conjunto de atributos, estrictamente iguales) únicos

In [76]:
total_unicos = len(pokemons.drop_duplicates())
total_unicos

802

**Ejercicio 04:** Obtener el total de IDs únicos en el dataset

In [79]:
len(pokemons["#"].unique())

721

**Ejercicio 05:** Obtener el total de tipos únicos de pokemones

In [85]:
len(pokemons.Type.unique())

18

12. Contabilización de Datos por Atributo

Pandas nos permite agrupar los datos por atributo y contabilizar los totales usando **.value_counts()**

¿Cuántos Pokémones hay por generación?

In [86]:
pokemons['Generation'].value_counts()

Generation
1    166
5    165
3    160
4    121
2    111
6     82
Name: count, dtype: int64